#!/usr/bin/bash

dir_path="/home/mostafa-hosny/Desktop/bashScript/ProjectBash/SimulateDataBase"
if [ -e "$dir_path" ]
then
    cd "$dir_path"
    echo "DBMS is ready "
else
    mkdir "$dir_path"
    cd "$dir_path"
    echo "DBMS is ready "
fi

while true
do
    PS3="Select an option: "
    echo -e "\n Main Menu:"
    select option in CreateDataBase ListDataBases ConnectedToDataBase DropDataBase Exit
    do
        case "$option" in 
        "CreateDataBase")
            read -p "enter database name : " dbName
            if [ -e "$dbName" ]
            then
                echo "DataBase is already exist"
                cd "$dir_path"
            else
                mkdir "$dbName"
                echo "DataBase is created successfully"
            fi
            break
            ;;
        "ListDataBases")
            echo "Available databases:"
            ls 
            break
            ;; 
        "ConnectedToDataBase")
            read -p "enter database name: " selectedDB
            if [ -e "$selectedDB" ]
            then
                cd "$selectedDB"
                echo "connected to $selectedDB "
                while true
                do
                    echo -e "\n Database: $selectedDB"
                    PS3="Select an option: "
                    select dbOption in CreateTable ListTables DropTable InsertIntoTable SelectFromTable DeleteFromTable UpdateTable BackToMain
                    do
                        case "$dbOption" in
                        "CreateTable")
                            read -p " Enter table name: " tableName
                            if [ -e "$tableName" ]
                            then
                                echo "Table already exists!"
                            else
                                read -p " Enter columns number : " colNum
				pk=0
                                for((i=1;i<=colNum;i++))
                                do
                                    line=""
                                    read -p " Enter column name $i : " colName
                                    line+="$colName"
                                    read -p " Enter column data type(int/string) : " colType
                                    line+=:"$colType"
				    if [[ "$pk" -eq 0 ]]
			            then
                                    read -p " Do you want to make this column PK(Y/N) : " checkPK
                                    	if [[  "yes" =~ "$checkPK" ]]
                                    	then
                                        	line+=:PK
						pk=1
                                    	fi
			            fi
                                    echo "$line" >> .$tableName"_Metadata"
                                done
                                touch "$tableName"
                                echo " Table '$tableName' created successfully!"
                            fi
                            break
                            ;;
                        "ListTables")
                            echo " Available tables:"
                            ls
                            break
                            ;;
                        "DropTable")
                            read -p " Enter table name to drop: " tableName
                            if [ -f "$tableName" ]
                            then
                                rm "$tableName"
                                echo "Table '$tableName' deleted successfully!"
                            else
                                echo " Table does not exist!"
                            fi
                            break
                            ;;
                        "InsertIntoTable")
                            read -p " Enter table name: " tableName
                            if [ -f "$tableName" ]
                            then
				echo "Column names:"
        			awk -F: '{print $1}' ".${tableName}_Metadata"
                                read -p "Enter values (seperated (,)): " values
                                echo "$values" >> "$tableName"
                                echo "Data inserted successfully!"
                            else
                                echo " Table does not exist!"
                            fi
                            break
                            ;;
                        "SelectFromTable")
                            read -p " Enter table name to view: " tableName
                            if [ -f "$tableName" ]
                            then

                                cat "$tableName"
                            else
                                echo " Table does not exist!"
                            fi
                            break
                            ;;
                        "DeleteFromTable")
                            read -p " Enter table name: " tableName
                            if [ -f "$tableName" ]
                            then
				pk_col=$(grep ":PK" ".${tableName}_Metadata" | cut -d':' -f1)
				echo "Primary key column: $pk_col"
				read -p " Enter $pk_col value to delete: " idValue
           			sed -i "/^$idValue,/d" "$tableName"
                                echo "Record deleted!"
                            else
                                echo " Table does not exist!"
                            fi
                            break
                            ;;
                        "UpdateTable")
                            read -p " Enter table name: " tableName
                            if [ -f "$tableName" ]
                            then
				pk_col=$(grep ":PK" ".${tableName}_Metadata" | cut -d':' -f1)
				echo "Primary key column: $pk_col"
				read -p " Enter $pk_col value to update: " idValue
			        echo "Column names:"
                                awk -F: '{print $1}' ".${tableName}_Metadata"
                                read -p " Enter new row values (separated(,)): " newRow
                                sed -i "s/^$idValue,.*/$newRow/" "$tableName"
                                echo "Record updated!"
                            else
                                echo " Table does not exist!"
                            fi
                            break
                            ;;
                        "BackToMain")
                            cd "$dir_path"
                            break 2
                            ;;
                        *)
                            echo " Invalid option!"
                            break
                            ;;
                        esac
                    done
                done
            else
                echo "DataBase is not exist "
            fi
            break
            ;;
        "DropDataBase")
            read -p "Enter database name to drop: " dbName
            if [ -e "$dbName" ]; then
                rm -r "$dbName"
                echo "Database $dbName deleted successfully"
            else
                echo "Database does not exist"
            fi
            break
            ;;
        "Exit")
            exit 0
            ;;
        *)
            echo "invalid option "
            break
            ;;
        esac
    done
done








